# https://zenmux.ai/docs/api/openai/openai-list-models.html
# https://zenmux.ai/docs/guide/advanced/reasoning.html
base_model = "dots-studio/dots3-note-prev"
reasoning_options = []

[cost]
input = 0
output = 0
cache_read = 0
