name = "Dots3-Note Preview (Free)"
description = "dots3-note-prev is a preview large language model designed for general conversation and complex tasks, with a focus on instruction following, reasoning, code generation, and multilingual interaction. As a preview release, its features and performance may continue to evolve."
release_date = "2026-08-17"
last_updated = "2026-08-17"
attachment = true
reasoning = true
temperature = false
tool_call = false
open_weights = true

[limit]
context = 393_100
output = 393_100

[modalities]
input = ["text", "image", "video", "audio"]
output = ["text"]

[[weights]]
label = "Hugging Face"
url = "https://huggingface.co/dots-studio/dots3-note-prev"
