# https://zenmux.ai/docs/api/openai/openai-list-models.html
# https://zenmux.ai/docs/guide/advanced/reasoning.html
base_model = "sapiens-ai/agnes-2.5-flash"
reasoning_options = []

[cost]
input = 0
output = 0
